import '@/app/styles/global.css'
import { Roboto } from 'next/font/google'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export const roboto = Roboto({ subsets: ['latin'], weight: ['100','300','400','500','700'] });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.className} antialiased`}>{children}</body>
    </html>
  )
}